window.opacity=0.5
[font]
normal = {family = "ComicShannsMonoNerdFont", style= "Regular"}
bold = {family = "ComicShannsMonoNerdFont", style= "Bold"}
italic = {family = "ComicShannsMonoNerdFont", style= "Italic"}

[colors.primary]
background = "#000000"
